# This is the default configuration for clock-rs.
# You can also leave out fields to produce the same effect.

[general]
color = "white"
interval = 200
blink = false
bold = false

[position]
horizontal = "center"
vertical = "center"

[date]
fmt = "%d-%m-%Y"
use_12h = false
utc = false
hide_seconds = false

[weather]
auto_location = false
refresh_interval_minutes = 10
temperature_unit = "celsius"

[now_playing]
enabled = false
refresh_interval_seconds = 5
